### ISSUE TITLE
Stencil coefficients typo for 1/12

### ISSUE THREAD

**Issue by ay1011** [aquaULB/solving_pde_mooc#22]
It should be -1/12. Understand that - 5 is correct since is it 2d.
![image](https://user-images.githubusercontent.com/13077482/176131251-d23c1ee7-58e7-4050-af49-f1f74932df29.png)
![image](https://user-images.githubusercontent.com/13077482/176132048-2d7cd64e-910a-4102-8923-8c34b54a36f0.png)

**Comment by bknaepen** [comment]
@ay1011 Good catch ! We'll update the drawing in the coming days. Thanks a lot.

**Comment by bknaepen** [comment]
@ay1011 Took some time but it's now fixed. Thanks again.
